### ISSUE TITLE
Component does not load after upgrade to 2023.7.0

### ISSUE THREAD

**Issue by renewoensdregt** [custom-components/remote_homeassistant#237]
Hi,
I just upgraded to Home Assistant 2023.7.0 (Supervisor 2023.07.1, Operating System 10.3, Frontend 20230705.0 - latest)

Getting an error: Invalid config
The following integrations and platforms could not be set up:
[remote_homeassistant](https://github.com/custom-components/remote_homeassistant) ([Show logs](https://palacehome.duckdns.org/config/logs?filter=remote_homeassistant))

Log shows:
Setup failed for custom integration remote_homeassistant: Unable to import component: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
component = integration.get_component()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
ComponentProtocol, importlib.import_module(self.pkg_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1147, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "/config/custom_components/remote_homeassistant/init.py", line 44, in
from .proxy_services import ProxyServices
File "/config/custom_components/remote_homeassistant/proxy_services.py", line 5, in
from homeassistant.core import SERVICE_CALL_LIMIT
ImportError: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)

Not sure if this will go away if the service calls reduce, or if this is an issue in the component.

**Comment by Nixxon123** [comment]
I have exactly the same problem!

**Comment by renewoensdregt** [comment]
Issue solved by solution provided in issue 236 (https://github.com/custom-components/remote_homeassistant/issues/236)

**Comment by lukas-hetzenecker** [comment]
Thanks, should be fixed in the latest release (3.9)
