### ISSUE TITLE
cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core'

### ISSUE THREAD

**Issue by cydiatec** [custom-components/remote_homeassistant#242]
Since updated to 2023.07 i think

**Comment by doricci** [comment]
Hello @cydiatec I'm using the version 2023.7.1 and I needed to upgrade to the latest version of this repository in order to fix the issue.

Now everything is working fine for my installation

**Comment by cydiatec** [comment]
> Hello @cydiatec I'm using the version 2023.7.1 and I needed to upgrade to the latest version of this repository in order to fix the issue.
> 
> 
> 
> Now everything is working fine for my installation
> 
> 

Hello doricci! Thanks for your quick reply! The Version of my Remote Integration was up to date on both systems. I removed the "remote_homeassistant" from my configuration.yaml, reinstalled the Integration added the Lines back into my configuration.yaml. Now it works. Thanks!
