### ISSUE TITLE
Remote HA Broken with 2023.7 beta

### ISSUE THREAD

**Issue by broyuken** [custom-components/remote_homeassistant#236]
I get the following breaking error when I upgrade my HA to 2023.7 beta. I have only upgraded the main system that I am sharing entities from, the one I am sharing to has not been upgraded. 

```
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/remote_homeassistant/proxy_services.py:5
Integration: remote_homeassistant (documentation, issues)
First occurred: 11:38:13 AM (1 occurrences)
Last logged: 11:38:13 AM

Setup failed for custom integration remote_homeassistant: Unable to import component: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/remote_homeassistant/__init__.py", line 44, in <module>
    from .proxy_services import ProxyServices
  File "/config/custom_components/remote_homeassistant/proxy_services.py", line 5, in <module>
    from homeassistant.core import SERVICE_CALL_LIMIT
ImportError: cannot import name 'SERVICE_CALL_LIMIT' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)

```

**Comment by acdcnow** [comment]
looks like that SERVICE_CALL_LIMIT has been changed or removed since the changes on response on service in 2023.7

Lets see if this remain in the release as well, if so then a change is needed in remote HA , as this will block me any upgrade to 2023.7.0.

**Comment by alphasixtyfive** [comment]
Could be related.

https://github.com/home-assistant/core/pull/94657

**Comment by malhalla** [comment]
Same problem with release of 2023.7

**Comment by TekFan** [comment]
I can confirm, this integration completely fails init in 2023.7
So it's broken for the time being.

**Comment by TheRealSimon42** [comment]
Same for me release 2023.7

**Comment by Arnsteinl** [comment]
Same here.....

**Comment by pcrednet** [comment]
same problem with 2023.7
need to disable integration

Thx.

**Comment by jplivingston08** [comment]
Same here.  I wish I checked before updating.  Going to restore from backup for now.

**Comment by mchangsp** [comment]
I have the same error in my log.
As a quick hack I did the following

- Go to the file custom_components/remote_homeassistant/proxy services.py
- Comment out line 5: # from homeassistant.core import SERVICE_CALL_LIMIT
- insert a new line: SERVICE_CALL_LIMIT = 10
- Reboot your HA 2023.7 instance

The remote_homeassistant integration should now load without problems during the reboot.

**Comment by jplivingston08** [comment]
@mchangsp - nice share !  I already downgraded.  For anyone that chooses to downgrade, here is the short that I followed to do it in a few minutes. https://youtube.com/shorts/iigi1ZgUSMo?feature=share

**Comment by goldbe4804** [comment]
updated today to 2023.7.0 same problem as above !!

**Comment by seanosteen** [comment]
I made the the modifications detailed by @mchangsp earlier today. This resolved the error and provides and is an excellent patch if you do not wish to downgrade.  Thank you!

@mchangsp 's fix:
- Go to the file custom_components/remote_homeassistant/proxy services.py
- Comment out line 5: # from homeassistant.core import SERVICE_CALL_LIMIT
- insert a new line: SERVICE_CALL_LIMIT = 10
- Reboot your HA 2023.7 instance

**Comment by loomyr** [comment]
Question: Should this fix only correct the inability to restart HomeAssistant due to the error in the custom_components, or should it also allow remote_homeassistant to continue working? In my case, the remote_homeassistant device is in the "connecting" state but is unable to connect to my remote instance.

**Comment by petez69** [comment]
> I have the same error in my log. As a quick hack I did the following
> 
> * Go to the file custom_components/remote_homeassistant/proxy services.py
> * Comment out line 5: # from homeassistant.core import SERVICE_CALL_LIMIT
> * insert a new line: SERVICE_CALL_LIMIT = 10
> * Reboot your HA 2023.7 instance
> 
> The remote_homeassistant integration should now load without problems during the reboot.

Thanks for the temp fix.....

**Comment by PelonVela** [comment]
Same problem as the rest.

**Comment by smithbill17** [comment]
As everyone has said, this is an issue with the released 2023.7.0 version. Thank you to @mchangsp with his workaround.

**Comment by Joakim-T** [comment]
> Question: Should this fix only correct the inability to restart HomeAssistant due to the error in the custom_components, or should it also allow remote_homeassistant to continue working? In my case, the remote_homeassistant device is in the "connecting" state but is unable to connect to my remote instance.

I applied the workaround fix on one of my Remote Assistant instances where i updated HA to 2023.7.
Then reloaded the integration on my main HA instance and it connected.

I have not updated my main instance to 2023.7 though.

**Comment by renewoensdregt** [comment]
workaround solved the issue!

**Comment by 1onord** [comment]
thanks to @mchangsp your fix fixes my Day ;)

**Comment by juanperez61** [comment]
thanks to @mchangsp

Muchisimas gracias :)

**Comment by wojked** [comment]
> * SERVICE_CALL_LIMIT

Thank you so much! saved my day too, I have created a PR so it would be easier to see
https://github.com/custom-components/remote_homeassistant/pull/238/files

**Comment by lpt2007** [comment]
When we can expect integration update to correct this error?

**Comment by lukas-hetzenecker** [comment]
Thanks for the reports

> When we can expect integration update to correct this error?

I will aim to release a new version either this evening, or tomorrow

**Comment by seanosteen** [comment]
I just pulled down version 3.9 on both my main and remote hosts. remote_homeassistant v 3.9 appears to be working as expected on both hass.io 2023.7.0 and docker 2030.7.0 instances.  Thank you @lukas-hetzenecker, @wojked, and @mchangsp for your quick work on this fix 👍

**Comment by lukas-hetzenecker** [comment]
Thanks for the confirmation and @wojked for the fix

**Comment by jplivingston08** [comment]
@lukas-hetzenecker - Really appreciate this integration.  It works so well and has allowed me to manage multiple HA instances from one view.  Thanks for developing and maintaining !

**Comment by jplivingston08** [comment]
@lukas-hetzenecker - Really appreciate this integration.  It works so well and has allowed me to manage multiple HA instances from one view.  Thanks for developing and maintaining !
